// <auto-generated />
using System;
using HelpDesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDesk.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Api.Models.Chamado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("categoria");

                    b.Property<Guid>("CodigoPublico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_publico")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataAbertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("IdColaborador")
                        .HasColumnType("bigint")
                        .HasColumnName("colaborador_id");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_empresa_id");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_id");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prioridade");

                    b.Property<DateTime?>("SlaPrazo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_prazo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPublico")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProduto");

                    b.ToTable("chamado");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCliente"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro_cliente");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdCliente");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEmpresa");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Colaborador", b =>
                {
                    b.Property<long>("IdColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdColaborador"));

                    b.Property<bool>("ColaboradorAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("colaborador_ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_colaborador");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro_colaborador");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("telefone");

                    b.HasKey("IdColaborador");

                    b.ToTable("colaborador");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Empresa", b =>
                {
                    b.Property<long>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEmpresa"));

                    b.Property<DateTime>("DataCadastroEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro_empresa");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("IdEmpresa");

                    b.ToTable("empresa");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Produto", b =>
                {
                    b.Property<long>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProduto"));

                    b.Property<DateTime>("DataAtualizacaoProduto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_produto");

                    b.Property<DateTime>("DataCadastroProduto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro_produto");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<bool>("ProdutoAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.HasKey("IdProduto");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.SlaCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("categoria");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_id");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("prioridade");

                    b.Property<TimeSpan>("TempoResolucao")
                        .HasColumnType("interval")
                        .HasColumnName("tempo_resolucao");

                    b.Property<TimeSpan>("TempoResposta")
                        .HasColumnType("interval")
                        .HasColumnName("tempo_resposta");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto", "Categoria", "Prioridade")
                        .IsUnique();

                    b.ToTable("sla_categorias");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Chamado", b =>
                {
                    b.HasOne("HelpDesk.Api.Models.Cliente", "Autor")
                        .WithMany()
                        .HasForeignKey("IdCliente");

                    b.HasOne("HelpDesk.Api.Models.Colaborador", "ColaboradorResponsavel")
                        .WithMany()
                        .HasForeignKey("IdColaborador");

                    b.HasOne("HelpDesk.Api.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("ColaboradorResponsavel");

                    b.Navigation("Empresa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Cliente", b =>
                {
                    b.HasOne("HelpDesk.Api.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.SlaCategoria", b =>
                {
                    b.HasOne("HelpDesk.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
